#RabbitMQ settings
spring:
    rabbitmq:
        host: ${SPRING_RABBITMQ_HOST}
        virtualhost: /
        port: 5672
        username: guest
        password: guest

rabbitmq:
    queue: rabbitmq.queue
    exchange: rabbitmq.exchange