apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f C:\Users\crist\git\clintech\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: clintech-mail-producer
  name: clintech-mail-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clintech-mail-producer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert -f C:\Users\crist\git\clintech\docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: clintech-mail-producer
    spec:
      containers:
        - env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq_host
          image: springboot-mail-producer
          name: mail-producer
          ports:
            - containerPort: 8090
          resources: {}
      restartPolicy: Always
status: {}
