apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f C:\Users\crist\git\clintech\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: clintech-front
  name: clintech-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clintech-front
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert -f C:\Users\crist\git\clintech\docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: clintech-front
    spec:
      containers:
        - image: clintech-front
          name: front-end
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
